### ISSUE TITLE
segv in grow_errors_buffer

### ISSUE THREAD

**Issue by robertswiecki** [google/kafel#3]
```
$ /tmp/k/dump_policy_bpf <SIGABRT.PC.7ffff6efc7ef.STACK.de2c48334.CODE.-6.ADDR.\(nil\).INSTR.mov____%r8d\,%eax.fuzz 
Compile error
=================================================================
==11651==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x611000000280 at pc 0x00000046c162 bp 0x7fff6c8c2900 sp 0x7fff6c8c20b0
READ of size 257 at 0x611000000280 thread T0
    #0 0x46c161 in printf_common(void*, char const*, __va_list_tag*) (/tmp/k/dump_policy_bpf+0x46c161)
    #1 0x4d7713 in __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) [clone .part.11] (/tmp/k/dump_policy_bpf+0x4d7713)
    #2 0x46b9c7 in printf_common(void*, char const*, __va_list_tag*) (/tmp/k/dump_policy_bpf+0x46b9c7)
    #3 0x46c9ba in __interceptor_vfprintf (/tmp/k/dump_policy_bpf+0x46c9ba)
    #4 0x46ca72 in __interceptor_fprintf (/tmp/k/dump_policy_bpf+0x46ca72)
    #5 0x50a895 in main /home/jagger/src/nsjail/kafel/tools/dump_policy_bpf/main.c:48:5
    #6 0x7f7d1a4c53f0 in __libc_start_main /build/glibc-jxM2Ev/glibc-2.24/csu/../csu/libc-start.c:291
    #7 0x419679 in _start (/tmp/k/dump_policy_bpf+0x419679)

0x611000000280 is located 0 bytes to the right of 256-byte region [0x611000000180,0x611000000280)
allocated by thread T0 here:
    #0 0x4d2b38 in realloc (/tmp/k/dump_policy_bpf+0x4d2b38)
    #1 0x50e83c in grow_errors_buffer /home/jagger/src/nsjail/kafel/context.c:154:18
    #2 0x50e83c in append_error /home/jagger/src/nsjail/kafel/context.c:195
    #3 0x526dfa in kafel_yyerror /home/jagger/src/nsjail/kafel/parser.y:406:5
    #4 0x526dfa in kafel_yyparse /home/jagger/src/nsjail/kafel/parser.c:2083
    #5 0x50c9ff in parse /home/jagger/src/nsjail/kafel/kafel.c:61:7
    #6 0x50c9ff in kafel_compile /home/jagger/src/nsjail/kafel/kafel.c:101
    #7 0x50a765 in main /home/jagger/src/nsjail/kafel/tools/dump_policy_bpf/main.c:42:12
    #8 0x7f7d1a4c53f0 in __libc_start_main /build/glibc-jxM2Ev/glibc-2.24/csu/../csu/libc-start.c:291

SUMMARY: AddressSanitizer: heap-buffer-overflow (/tmp/k/dump_policy_bpf+0x46c161) in printf_common(void*, char const*, __va_list_tag*)
Shadow bytes around the buggy address:
  0x0c227fff8000: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c227fff8010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c227fff8020: 00 00 fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c227fff8030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c227fff8040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c227fff8050:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c227fff8060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c227fff8070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c227fff8080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c227fff8090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c227fff80a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==11651==ABORTING
```

Testcase attached
[SIGABRT.PC.7ffff6efc7ef.STACK.de2c48334.CODE.-6.ADDR.(nil).INSTR.mov____%r8d,%eax.txt](https://github.com/google/kafel/files/649364/SIGABRT.PC.7ffff6efc7ef.STACK.de2c48334.CODE.-6.ADDR.nil.INSTR.mov____.r8d.eax.txt)

**Comment by happyCoder92** [comment]
Fixed with e1d4cd5
